# Generated by Django 5.0.6 on 2024-06-22 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0002_testetable_delete_funcionario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TesteTable',
        ),
    ]
