# Generated by Django 5.0.6 on 2024-06-24 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backoffice', '0003_delete_testetable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('email', models.EmailField(max_length=254)),
                ('contato', models.CharField(max_length=20)),
                ('nota', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
