# Generated by Django 5.0.6 on 2024-06-24 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='tipo',
            field=models.CharField(choices=[('Consulta', 'Consulta'), ('Visita', 'Visita'), ('Avaliação Física', 'Avaliação Física')], max_length=50),
        ),
    ]
