# Generated by Django 5.0.6 on 2024-06-27 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0006_cadastroimage_imageupdatelog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastroimage',
            name='uploaded_at',
        ),
        migrations.AlterField(
            model_name='cadastroimage',
            name='image',
            field=models.ImageField(upload_to='cadastro_images'),
        ),
        migrations.DeleteModel(
            name='ImageUpdateLog',
        ),
    ]
