# Generated by Django 5.0.6 on 2024-06-27 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0007_remove_cadastroimage_uploaded_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CadastroImage',
        ),
    ]
