# Generated by Django 5.0.6 on 2024-06-27 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0010_contacto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacto',
            old_name='data_contato',
            new_name='data_contacto',
        ),
    ]
