# Generated by Django 5.0.6 on 2024-06-27 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0011_rename_data_contato_contacto_data_contacto'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapaAulas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='mapas_aulas/')),
                ('pdf', models.FileField(upload_to='mapas_aulas/')),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
