# Generated by Django 5.0.6 on 2024-06-28 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0012_mapaaulas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapaaulas',
            name='data_atualizacao',
        ),
    ]
