# Generated by Django 5.0.6 on 2024-06-28 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0014_alter_mapaaulas_imagem_alter_mapaaulas_pdf'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MapaAulas',
        ),
    ]
