# Generated by Django 5.0.6 on 2024-06-28 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0016_contacto_estado_contacto_validado_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='data_acao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='estado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='usuario_acao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
