# Generated by Django 5.0.6 on 2024-06-28 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0017_cadastro_data_acao_cadastro_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='data_acao',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
